// const { SlashCommandBuilder } = require('@discordjs/builders');
const { SlashCommandBuilder } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('joke')
		.setDescription('Tells you a corny joke!'),
	async execute(interaction) {
		return interaction.reply(tell_joke())
	}
};

function tell_joke() {
	let random_number = Math.floor(Math.random() * jokes.length);
	return (jokes[random_number])
}

let jokes = [
	"Why can't a leopard hide?\n||Because he's always spotted.||",
	"What do you call an illegally parked frog?\n||Toad.||",
	"How do moths swim?\n|| Using the butterfly stroke.||",
	"How many tickles does it take to make an octopus laugh?\n||10 tickles.||",
	"Do you know the story about the chicken that crossed the road? \n|| Me neither, I couldn't follow it.||",
	"What do you get from a pampered cow?\n||Spoiled milk!||",
	"Where do baby cats learn to swim?\n||The kitty pool.||",
	"Why are spiders so smart?\n|| They can find everything on the web.||",
	"How can a leopard change his spots?\n|| By moving.||",
	"What did the duck say when it bought chapstick?\n||'Put it on my bill!'||",
	"What does a cow use to do math?\n|| A cow-culator.||",
	"What would bears be without the letter B? \n||Ears.||",
	"What do you get if you cross an angry sheep with a moody cow? \n||An animal that's in a baaaaaaaaad moooooooood.||",
	"Can a kangaroo jump higher than the Empire State Building?\n||Of course! Buildings can't jump.||",
	"What did the alpaca say to his date?\n||'Want to go on a picnic? Alpaca lunch.'||",
	"Why do seagulls fly over the sea? \n|| If they flew over the bay, they'd be called bagels.||",
	"Why are snails bad at racing? \n|| They're sluggish.||",
	"What do you call a penguin in the White House? \n||Lost.||",
	"What do you call a kangaroo's lazy joey? \n||A pouch potato.||",
	"How does a boar sign its name?\n|| With a pig pen.||",
	"Why should you never trust a carp's excuse? \n||They always seem a little fishy.||",
	"Did you hear that I'm reading a book about anti-gravity?\n|| It's impossible to put down.||",
	"Which is faster, hot or cold?\n|| Hot, because you can catch a cold.||",
	"What's brown and sounds like a bell?\n|| Dung!||",
	"What did the photon say when asked if she needed to check a bag?\n|| 'No thanks, I'm traveling light!'||",
	"How do you organize a space party? \n|| You planet.||",
	"Did you know milk is the fastest liquid on earth? \n|| It's pasteurized before you even see it.||",
	"What did one ocean say to the other ocean? \n|| Nothing, they just waved.||",
	"Why did everyone enjoy being around the volcano? \n|| It's just so lava-ble.||",
	"What kind of music do the planets listen to?\n||Nep-tunes!||",
	"What did the big flower say to the tiny flower?\n||“Hey there bud!”||",
	"Why are skeletons so calm?\n||Because nothing gets under their skin.||",
	"What did Mars ask Saturn?\n||“Hey, can you give me a ring some time?”||",
	"Why can't you trust an atom?\n||Because they make up everything.||",
	"What do clouds do when they become rich?\n||They make it rain!||",
	"Why shouldn't you make fun of a paleontologist?\n||Because you will get Jurasskicked.||",
	"Want to hear a potassium joke?\n||K.||",
	"Why are helium, curium, and barium the medical elements?\n||Because if you can't heal-ium or cure-ium, you bury-um.||",
	"How did the chemist feel about oxygen and potassium hanging out?\n||OK.||",
	"What is it called when Silver Surfer and Iron Man team up?\n||Alloys.||",
	"What does a baby computer call his father?\n||Data.||",
	"Did you hear about the power outlet that got into a fight with a power cord?\n||He thought he could socket to him.||",
	"Why did the computer have no money left?\n||Someone cleaned out its cache!||",
	"What's a computer's favorite snack?\n||Microchips!||",
	"What do you call monkeys with a shared Amazon account?\n||Prime mates.||",
	"Why should you never use “beef stew” as a password?\n||It's not stroganoff.||",
	"What do you call your grandma's number on speed dial?\n||Instagram.||",
	"What's another name for an iPhone power cord?\n||Apple juice.||",
	"What do you call a TV vaccination?\n||A screen-shot.||",
	"Why did the PowerPoint presentation cross the road?\n||To get to the other slide.||",
	"Why did the computer always play “Someone Like You?”\n||It was a Dell.||",
	"Why did the laptop show up late to school?\n||It had a hard drive.||",
	"What do you call an iPhone with no sense of humor?\n||Too Siri-ous.||",
	"Why was the cell phone's camera blurry?\n||It had lost its contacts.||",
	"Why was the man fired from the keyboard factory?\n||He wasn't working with enough shifts.||",
	"Why couldn't the computer buy a new pair of jeans?\n||It had spent all its cache.||",
	"Why do smartphones ring?\n||Because they can't talk.||",
	"What do you call a fake noodle?\n||An impasta.||",
	"Why didn't the melons get married?\n||Because they cantaloupe.||",
	"Why couldn't the sesame seed get off the hill?\n||It was on a roll.||",
	"What kind of egg did the evil chicken lay?\n||A deviled egg.||",
	"Why is the hot pepper the nosiest vegetable?\n||It can't help but get jalapéno space.||",
	"Why do crabs never share their lobsters?\n||They're shellfish.||",
	"What do you call a happy camper?\n||A Jolly Rancher.||",
	"Why are mushrooms always invited to parties?\n||They're a fungi.||",
	"What do you call a fancy seafood meal?\n||So-fish-ticated.||",
	"What do you call a sad strawberry?\n||A blueberry.||",
	"Why did the banana go to the hospital?\n||He wasn't peeling well.||",
	"What do you call a pig that knows karate?\n||A pork chop.||",
	"Where do pancakes rise?\n||In the yeast.||",
	"What is a mummy's favorite food?\n||Wraps.||",
	"What kind of fruit do you bring while sailing?\n||Naval oranges.||",
	"What do frogs order at restaurants?\n||French flies.||",
	"What do you call a fake noodle?\n||Impasta.||",
	"What's orange and sounds like a parrot?\n||A carrot.||",
	"How do I look?\n||With your eyes.||",
	"How do you get a country girl's attention?\n||A tractor.||",
	"Why is the cemetery so popular?\n||People are just dying to get in there!||",
	"What was the child who wouldn't nap guilty of?\n||Resisting a rest!||",
	"Where do cows go for entertainment?\n||To the moovies.||",
	"What did the zero say to the eight?\n||“Nice belt.”||",
	"What do you call a pile of cats?\n||A meow-tain.||",
	"What do you call a flea in France?\n||A paris-ite.||",
	"What runs around a baseball field but never moves?\n||A fence.||",
	"Why was the calendar afraid?\n||Its days were numbered.||",
	"What time did the man go to the dentist?\n||Tooth hurt-y.||",
	"Why didn't the skeleton climb the mountain?\n||It didn't have the guts.||",
	"My dad told me a joke about boxing.\n||I guess I missed the punch line.||",
	"What kind of car does an egg drive?\n||A yolkswagen.||",
	"How do you follow Will Smith in the snow?\n||You follow the fresh prints.||",
	"How do celebrities stay cool?\n||They have many fans.||",
	"What do you call it when Batman skips church?\n||Christian Bale.||",
	"What's Forrest Gump's Facebook password?\n||1forest1.||",
	"Did you hear about the man who fell into an upholstery machine?\n||He's fully recovered.||",
	"Why did the coach go to the bank?\n||To get his quarter back.||",
	"Why does Snoop Dogg always carry an umbrella?\n||Fo' drizzle.||",
	"What did the fisherman say to the magician?\n||“Pick a cod, any cod.”||",
	"What do you call a security guard outside of a Samsung store?\n||Guardians of the Galaxy.||",
	"Why can't you give Elsa a balloon?\n||Because she'd just let it go.||",
	"How does Reese eat cereal?\n||Witherspoon.||",
	"What do you call a nearsighted cowboy?\n||Squint Eastwood.||",
	"Why did the Jedi cross the road?\n||To get to the dark side.||",
	"What do you call a freshly fallen tree?\n||Die Hard.||",
	"Did you hear about the new pirate movie?\n||It's rated “Arrrrrrr.”||",
	"Which bear is the most condescending?\n||A pan-duh!||",
	"What kind of noise does a witch's vehicle make?\n||Brrrroooom, brrroooom.||"
]


